import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { LayoutDashboard, ListChecks, LogOut, Merge, ShieldCheck, Trophy } from 'lucide-react'
import { cn } from '@/lib/utils'

const links = [{ to: '/admin', label: 'Übersicht', icon: LayoutDashboard, end: true }, { to: '/admin/tournaments', label: 'Turniere', icon: ListChecks }, { to: '/admin/players/merge', label: 'Spieler zusammenführen', icon: Merge }]

export function AdminLayout() {
  const location = useLocation()
  return <div className="min-h-dvh bg-muted/30"><header className="border-b bg-card"><div className="page-shell flex min-h-16 items-center justify-between py-3"><Link to="/admin" className="flex items-center gap-3 font-semibold"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-primary text-primary-foreground"><ShieldCheck size={19} aria-hidden="true" /></span>Kickertool Verwaltung</Link><Link className="inline-flex min-h-11 items-center gap-2 rounded-md px-3 text-sm text-muted-foreground hover:bg-muted hover:text-foreground" to="/"><LogOut size={16} aria-hidden="true" />Admin verlassen</Link></div></header><div className="page-shell grid gap-6 lg:grid-cols-[15rem_1fr]"><aside className="hidden lg:block"><nav aria-label="Admin-Navigation" className="sticky top-6 space-y-1">{links.map(link => <NavLink key={link.to} to={link.to} end={link.end} className={({ isActive }) => cn('flex min-h-11 items-center gap-3 rounded-md px-3 text-sm', isActive ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground')}><link.icon size={17} aria-hidden="true" />{link.label}</NavLink>)}</nav></aside><main className="min-w-0"><div className="mb-5 flex items-center gap-2 overflow-x-auto lg:hidden">{links.map(link => <NavLink key={link.to} to={link.to} end={link.end} className={({ isActive }) => cn('inline-flex min-h-11 shrink-0 items-center gap-2 rounded-md border px-3 text-sm', isActive ? 'border-primary bg-primary text-primary-foreground' : 'bg-card text-muted-foreground')}><link.icon size={16} aria-hidden="true" />{link.label}</NavLink>)}</div><div aria-label="Aktueller Admin-Pfad" className="sr-only">{location.pathname}</div><Outlet /></main></div></div>
}
