import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowLeftRight, CheckCircle2, Search, ShieldAlert } from 'lucide-react'
import { ApiError, confirmMerge, previewMerge, searchPlayers } from '@/api/client'
import type { MergeResult, Player } from '@/api/types'
import { useAdminSession } from '@/app/providers'
import { Alert } from '@/components/ui/alert'
import { AlertDialog } from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Command, CommandItem, CommandList } from '@/components/ui/command'
import { Input } from '@/components/ui/input'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Skeleton } from '@/components/ui/skeleton'
import { formatDecimal } from '@/lib/utils'

export function PlayerMergePage() {
  const session = useAdminSession()
  const [sourceQuery, setSourceQuery] = useState('')
  const [targetQuery, setTargetQuery] = useState('')
  const [sourceResults, setSourceResults] = useState<Player[]>([])
  const [targetResults, setTargetResults] = useState<Player[]>([])
  const [source, setSource] = useState<Player | null>(null)
  const [target, setTarget] = useState<Player | null>(null)
  const [loadingSide, setLoadingSide] = useState<'source' | 'target' | null>(null)
  const [result, setResult] = useState<MergeResult | null>(null)
  const [planToken, setPlanToken] = useState('')
  const [targetName, setTargetName] = useState('')
  const [checked, setChecked] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  useEffect(() => { const timer = setTimeout(() => { if (sourceQuery.trim().length >= 2) { setLoadingSide('source'); searchPlayers(sourceQuery).then(setSourceResults).catch(() => setSourceResults([])).finally(() => setLoadingSide(null)) } else setSourceResults([]) }, 250); return () => clearTimeout(timer) }, [sourceQuery])
  useEffect(() => { const timer = setTimeout(() => { if (targetQuery.trim().length >= 2) { setLoadingSide('target'); searchPlayers(targetQuery).then(setTargetResults).catch(() => setTargetResults([])).finally(() => setLoadingSide(null)) } else setTargetResults([]) }, 250); return () => clearTimeout(timer) }, [targetQuery])
  const choose = (side: 'source' | 'target', player: Player) => { if (source?.id === player.id || target?.id === player.id) { setError('Quelle und Ziel müssen unterschiedliche Spieler sein.'); return } if (side === 'source') { setSource(player); setSourceQuery(player.displayName); setSourceResults([]) } else { setTarget(player); setTargetQuery(player.displayName); setTargetResults([]) } setError(''); setResult(null) }
  const swap = () => { const oldSource = source; setSource(target); setTarget(oldSource); const oldQuery = sourceQuery; setSourceQuery(targetQuery); setTargetQuery(oldQuery); setResult(null); setError('') }
  const createPreview = async () => { if (!source || !target || source.id === target.id) { setError('Bitte zwei unterschiedliche Spieler auswählen.'); return } setError(''); try { const value = await previewMerge(session.csrf, source.id, target.id); setResult(value.result); setPlanToken(value.token); setTargetName(''); setChecked(false) } catch (value) { setError(value instanceof Error ? value.message : 'Vorschau konnte nicht erstellt werden.') } }
  const executeMerge = async () => { if (!planToken || !checked || !result || targetName !== result.targetDisplayName) { setError('Bitte Zielnamen exakt eingeben und die Prüfung bestätigen.'); return } try { const value = await confirmMerge(session.csrf, planToken, targetName); setSuccess(value.alreadyMerged ? 'Diese Zusammenführung war bereits verarbeitet.' : 'Spieler erfolgreich zusammengeführt.'); setResult(value.result); setDialogOpen(false) } catch (value) { setError(value instanceof ApiError && value.status === 409 ? 'Die Vorschau ist veraltet. Bitte neu suchen und eine neue Vorschau erstellen.' : value instanceof Error ? value.message : 'Zusammenführung fehlgeschlagen.') } }
  return <div><div className="mb-6"><p className="text-sm font-medium text-primary">Datenpflege</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Spieler zusammenführen</h1><p className="mt-2 max-w-2xl text-muted-foreground">Dieser Spieler wird entfernt und seine Ergebnisse werden auf den Zielspieler übertragen. Der Zielspieler bleibt bestehen.</p></div>{error && <Alert variant="destructive" className="mb-4"><div className="flex items-center gap-3"><ShieldAlert aria-hidden="true" />{error}</div></Alert>}{success && <Alert variant="success" className="mb-4"><div className="flex items-center gap-3"><CheckCircle2 aria-hidden="true" />{success}</div></Alert>}<div className="grid gap-4 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><PlayerPane side="source" title="Dieser Spieler wird entfernt" query={sourceQuery} setQuery={setSourceQuery} selected={source} results={sourceResults} loading={loadingSide === 'source'} onChoose={player => choose('source', player)} onClear={() => { setSource(null); setSourceQuery('') }} /><div className="flex items-center justify-center"><div className="flex flex-col items-center gap-2"><span className="text-sm font-semibold text-muted-foreground">wird übertragen nach</span><Button variant="outline" onClick={swap}><ArrowLeftRight aria-hidden="true" />Richtung tauschen</Button></div></div><PlayerPane side="target" title="Dieser Spieler bleibt bestehen" query={targetQuery} setQuery={setTargetQuery} selected={target} results={targetResults} loading={loadingSide === 'target'} onChoose={player => choose('target', player)} onClear={() => { setTarget(null); setTargetQuery('') }} /></div><div className="mt-6 flex flex-col items-center gap-3"><Button disabled={!source || !target || source.id === target.id} onClick={createPreview}><Search aria-hidden="true" />Vorschau erstellen</Button>{(!source || !target) && <p className="text-sm text-muted-foreground">Wähle Quelle und Ziel aus, um die Vorschau zu öffnen.</p>}</div>{result && <MergePreview result={result} targetName={targetName} setTargetName={setTargetName} checked={checked} setChecked={setChecked} onOpenConfirm={() => setDialogOpen(true)} />}<AlertDialog open={dialogOpen} title="Zusammenführung endgültig bestätigen?" description={result ? result.sourceDisplayName + ' wird auf ' + result.targetDisplayName + ' übertragen. GroupStandings bleiben erhalten.' : ''} confirmLabel="Zusammenführung ausführen" destructive onCancel={() => setDialogOpen(false)} onConfirm={executeMerge} /></div>
}

function PlayerPane({ side, title, query, setQuery, selected, results, loading, onChoose, onClear }: { side: 'source' | 'target'; title: string; query: string; setQuery: (value: string) => void; selected: Player | null; results: Player[]; loading: boolean; onChoose: (player: Player) => void; onClear: () => void }) {
  return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle><CardDescription>{side === 'source' ? 'Alle Zuordnungen des Quellspielers werden übertragen.' : 'Dieser Datensatz bleibt kanonisch.'}</CardDescription></CardHeader><CardContent>{selected ? <div className="rounded-md border border-primary/40 bg-primary/5 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{selected.displayName}</h2><p className="mt-1 text-xs text-muted-foreground">{selected.aliases.length} Namensvarianten</p></div><Button size="sm" variant="outline" onClick={onClear}>Ändern</Button></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Turniere" value={selected.tournamentCount} /><Metric label="Spiele" value={selected.gamesPlayed ?? '—'} /><Metric label="Punkte" value={cents(selected.totalPointsCents)} /><Metric label="Punkte/Spiel" value={cents(selected.pointsPerGameCents)} /><Metric label="Tordifferenz" value={selected.goalDifference ?? '—'} /></dl></div> : <><Popover><PopoverTrigger><label className="relative block"><span className="sr-only">{side === 'source' ? 'Quellspieler' : 'Zielspieler'} suchen</span><Search className="absolute left-3 top-3.5 text-muted-foreground" size={17} aria-hidden="true" /><Input className="pl-10" value={query} onChange={event => setQuery(event.target.value)} placeholder="Mindestens 2 Zeichen" role="combobox" aria-autocomplete="list" aria-expanded={!loading && results.length > 0} /></label></PopoverTrigger>{!loading && results.length > 0 && <PopoverContent><Command aria-label="Suchergebnisse"><CommandList>{results.map(player => <CommandItem key={player.id} type="button" onClick={() => onChoose(player)}><span><span className="font-medium">{player.displayName}</span>{player.matchedAlias && <span className="ml-2 text-xs text-muted-foreground">Alias: {player.matchedAlias}</span>}</span><span className="ml-auto text-xs tabular text-muted-foreground">{player.tournamentCount} Turniere</span></CommandItem>)}</CommandList></Command></PopoverContent>}</Popover>{query.trim().length < 2 && <p className="mt-3 text-sm text-muted-foreground">Mindestens 2 Zeichen eingeben. Suche umfasst kanonische Namen und Aliase.</p>}{loading && <div className="mt-3 space-y-2"><Skeleton className="h-12" /><Skeleton className="h-12" /></div>}{!loading && query.trim().length >= 2 && results.length === 0 && <p className="mt-3 text-sm text-muted-foreground">Keine passenden Spieler gefunden.</p>}</>}</CardContent></Card>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="tabular font-medium">{value}</dd></div> }
function cents(value: number | null | undefined) { return value === null || value === undefined ? '—' : formatDecimal(value / 100) }
function MergePreview({ result, targetName, setTargetName, checked, setChecked, onOpenConfirm }: { result: MergeResult; targetName: string; setTargetName: (value: string) => void; checked: boolean; setChecked: (value: boolean) => void; onOpenConfirm: () => void }) {
  return <Card className="mt-8"><CardHeader><CardTitle>Vorschau prüfen</CardTitle><CardDescription>{result.sourceDisplayName} wird übertragen nach {result.targetDisplayName}. Die GroupStandings werden nicht gelöscht, nur die Spielerzuordnung ändert sich.</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-3"><AggregateCard label="Quelle vorher" value={result.sourceBefore} /><AggregateCard label="Ziel vorher" value={result.targetBefore} /><AggregateCard label="Ziel nachher" value={result.targetAfter} highlight /></div><dl className="mt-6 grid gap-3 border-t pt-5 text-sm sm:grid-cols-4"><Metric label="Weitere Namensvarianten" value={result.transferredAliases} /><Metric label="Verknüpfte Quelldatensätze" value={result.transferredSourceIdentities} /><Metric label="Übertragene Turnierergebnisse" value={result.transferredAllocations} /><Metric label="Bereits beiden zugeordnete Ergebnisse" value={result.deduplicatedAllocations} /></dl>{result.deduplicatedAllocations > 0 && <Alert variant="warning" className="mt-5"><div className="flex items-start gap-3"><AlertTriangle aria-hidden="true" /><p><strong>{result.deduplicatedAllocations} gemeinsame Ergebnisse</strong> werden nach der Zusammenführung nur einmal gezählt.</p></div></Alert>}<div className="mt-6 max-w-lg"><label className="text-sm font-medium" htmlFor="target-name-confirm">Exakten Zielnamen eingeben</label><Input id="target-name-confirm" className="mt-2" value={targetName} onChange={event => setTargetName(event.target.value)} autoComplete="off" /><label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><Checkbox checked={checked} onChange={event => setChecked(event.target.checked)} />Ich habe Quelle und Ziel geprüft.</label><Button className="mt-4" disabled={!checked || targetName !== result.targetDisplayName} onClick={onOpenConfirm}>Zusammenführung prüfen und ausführen</Button></div></CardContent></Card>
}
function AggregateCard({ label, value, highlight = false }: { label: string; value: MergeResult['sourceBefore']; highlight?: boolean }) {
  return <article className={highlight ? 'rounded-md border-2 border-primary/40 bg-primary/5 p-4' : 'rounded-md border p-4'}><h3 className="font-medium">{label}</h3><dl className="mt-3 space-y-2 text-sm"><Metric label="Turniere" value={value?.tournamentCount ?? '—'} /><Metric label="Spiele" value={value?.gamesPlayed ?? '—'} /><Metric label="Punkte" value={cents(value?.totalPointsCents)} /><Metric label="Punkte/Spiel" value={cents(value?.pointsPerGameCents)} /><Metric label="Tordifferenz" value={value?.goalDifference ?? '—'} /></dl></article>
}
